### ISSUE TITLE
Type error , tried everything nothing working 

### ISSUE THREAD

**Issue by skillhacker-code** [stlukey/whispercpp.py#11]
File "C:\Program Files\Python310\lib\pathlib.py", line 583, in _parse_args
    raise TypeError(
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>

**Comment by DanielLaV** [comment]
Running into this same issue.

**Comment by aidanperkins** [comment]
same problem. 
removing the .encode('utf-8') in whispercpp.pyx should fix the type issue. 
def __init__(self, model=DEFAULT_MODEL, pb=None):
        model_fullname = f'ggml-{model}.bin'.encode('utf8')

**Comment by transfluxus** [comment]
where is that file?

**Comment by abbygriffiths** [comment]
Bump. `pip show whispercpp` is of no use since the library only shows a .so dynamic library instead of the actual .pyx file.

**Comment by Rookiee111** [comment]
still facing the same issue, 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "whispercpp.pyx", line 89, in whispercpp.Whisper.__init__
  File "whispercpp.pyx", line 34, in whispercpp.download_model
  File "whispercpp.pyx", line 31, in whispercpp.model_exists
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 851, in joinpath
    return self._make_child(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 616, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 583, in _parse_args
    raise TypeError(
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>

**Comment by stlukey** [comment]
#14 has now been merged and the issue should be resolved. Please let me know if your are having any further issues.
